/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./App.tsx",
    "./index.tsx",
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./scripts/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#11d452",
        nord0: "#2e3440",
        nord1: "#3b4252",
        nord2: "#434c5e",
        nord3: "#4c566a",
        nord4: "#d8dee9",
        nord5: "#e5e9f0",
        nord6: "#eceff4",
        nord7: "#8fbcbb",
        nord8: "#88c0d0",
        nord9: "#81a1c1",
        nord10: "#5e81ac",
        nord11: "#bf616a",
        nord12: "#d08770",
        nord13: "#ebcb8b",
        nord14: "#a3be8c",
        nord15: "#b48ead",
        "deep-bg": "#13151a",
        "deep-card": "#1c212b",
        "deep-search": "#0d0f14",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};